credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          description: "deployKey"
          id: "deployKey"
          privateKeySource:
            directEntry:
              privateKey: |
                -----BEGIN OPENSSH PRIVATE KEY-----
                b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
                NhAAAAAwEAAQAAAQEA0pmAU3KsG5ab9q3QYnO99wB59YDTy0UhG4ns7tY3mnQDWSD6/f0k
                y5/wlgUx/v9khPDrfd9vh6jJvwjKszQl9gR3qNrCG80whdPpsyL7dSjSOI3MJ3YoGfT6nz
                8+NYeRGNj0AnjrXDTVxdAJN89UgQj44+nNIZavb+83+yQ23kKSISqvD/NXPDFXt7jPQUua
                zldRK1iLr/DIbH98F+9xCkwJ/cpl3QR066BQFEizElwYjPGL9yQMuRkOAaSjhAkNqwMv/p
                iJRHe+0qurMr6e9PRPT8zjigh7dnw7a6tzGDl+Qp2iOoR90fkiLD10fp3XOtIbu4Gmf7Dw
                KQ12jV80nQAAA9gv44CCL+OAggAAAAdzc2gtcnNhAAABAQDSmYBTcqwblpv2rdBic733AH
                n1gNPLRSEbiezu1jeadANZIPr9/STLn/CWBTH+/2SE8Ot932+HqMm/CMqzNCX2BHeo2sIb
                zTCF0+mzIvt1KNI4jcwndigZ9PqfPz41h5EY2PQCeOtcNNXF0Ak3z1SBCPjj6c0hlq9v7z
                f7JDbeQpIhKq8P81c8MVe3uM9BS5rOV1ErWIuv8Mhsf3wX73EKTAn9ymXdBHTroFAUSLMS
                XBiM8Yv3JAy5GQ4BpKOECQ2rAy/+mIlEd77Sq6syvp709E9PzOOKCHt2fDtrq3MYOX5Cna
                I6hH3R+SIsPXR+ndc60hu7gaZ/sPApDXaNXzSdAAAAAwEAAQAAAQBHv/RweckZPR611FIC
                uNwnownqEpIV1t+Iulz2ohUfkhbx7sKUdgJrPXqCIhL+hZSBlnMk11LwLRlO9HfaxhGI18
                zMwnsPbcDyV1hvp6N0LwwwKF89sovHDCe2yZ0wL5fHl2LK1Nea+oU6d74sPX7U13G0dJtm
                rifnQuEXtybaYcWLbyFI6v/P2Tffrn04din4hvE9IKc9h848twg7avyB8c/wyqgx9aogi7
                pD1BXPtxy2S0p6Jp7ATVBG1LtWEelE64SAjLCemzZIFHHP0+9l201b8pwgV5ID/5/8jm9n
                fcvdVFOpFpcJUk8o5yIpznUvuYIoS0C+O5rDdPqdGlghAAAAgEEhNhx4MelUnTINDJmdY0
                Md3Oov577Ic2sWSC6z19sumEFVn1Y1MpOYm3jR4+Xh0xspjiXRV2nf0SnPB3ENUYGMW2GY
                oWHkiHGWdQB9dEyS+nEY9P7u7bCsXeUHGQq1V5R/Oxgcxjp/0IH0bKp1ESauzHBKHCsiW+
                na29kl6L9qAAAAgQDvxb/w14dOpNSuUoku6m0AyevjGxTYFLdeoWSLE+c5ghB97IsAteXr
                xGJ7U7EtDHvhcc4yz0HvBovwaaHD6oT3hbeeG1f7w4tYiK/LjfjlqvClO67pi9A00NKjcQ
                6CQkhL6tmcaPqdTVqDoklfs5dQsVOpDEiBiMxARIjADoOcxwAAAIEA4NpO/QzlYBAO4ilm
                siVM00SGGegRYxgSHMkeXsfTHCRddpMBp2p4AsyNOzZiNqN97cHMqSr9QXtg/XFuEr/L0m
                AgcY3vjC6DC4ls2uqxANAVPQcvOD1Ie+XCIT2uUqL53zSiKlqjpl3OIGHjz59zIzizWc6H
                1Mf5CcrWvFeLF3sAAAAdYXdpZWNoZXJ0QE1BQzA2NS5rYXJzdGFkdC5uZXQBAgMEBQY=
                -----END OPENSSH PRIVATE KEY-----
          scope: GLOBAL
          username: "elastic2-awiechert"
jenkins:
  systemMessage: "JCasC Setup\n\n"
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: ${adminpw:-password}
       - id: alex
         password: ${adminpw:-password}
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "Agent/Build:admin"
      - "Agent/Configure:admin"
      - "Agent/Connect:admin"
      - "Agent/Create:admin"
      - "Agent/Delete:admin"
      - "Agent/Disconnect:admin"
      - "Credentials/Create:admin"
      - "Credentials/Delete:admin"
      - "Credentials/ManageDomains:admin"
      - "Credentials/Update:admin"
      - "Credentials/View:admin"
      - "Job/Build:admin"
      - "Job/Cancel:admin"
      - "Job/Configure:admin"
      - "Job/Create:admin"
      - "Job/Delete:admin"
      - "Job/Discover:admin"
      - "Job/Move:admin"
      - "Job/Read:admin"
      - "Job/ViewStatus:admin"
      - "Job/Workspace:admin"
      - "Lockable Resources/Reserve:admin"
      - "Lockable Resources/Unlock:admin"
      - "Lockable Resources/View:admin"
      - "Overall/Administer:admin"
      - "Overall/Read:admin"
      - "Overall/Read:authenticated"
      - "Run/Delete:admin"
      - "Run/Replay:admin"
      - "Run/Update:admin"
      - "SCM/Tag:admin"
      - "View/Configure:admin"
      - "View/Create:admin"
      - "View/Delete:admin"
      - "View/Read:admin"
  crumbIssuer:
unclassified:
  location:
    url: http://localhost
    adminAddress: admin@example.com


# tool:
#   git:
#     installations:
#     - home: "git"
#       name: "Default"
#   maven:
#     installations:
#     - name: "Maven 3"
#       properties:
#       - installSource:
#           installers:
#             - maven:
#                 id: "3.5.4"
jobs:
  - script: |
      freeStyleJob("SeedJob") {
          scm {
              git {
                  remote {
                      name('origin')
                      url('git@github.com:elastic2ls-awiechert/terraform-ecs-jenkins-backend.git')
                      credentials("deployKey")
                  }
                  branches('*/MD-70')
              }
          }
          triggers {
              scm('H/5 * * * *')
          }
          steps {
              dsl {
                  external("seedjob.jenkinsfile")
                  removeAction('DELETE')
                  removeViewAction('DELETE')
              }
          }
      }